name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: helsingborg-stad/municipio-deploy/3.0@master
      with:
        deploy-host: ${{ secrets.DEPLOY_REMOTE_HOST_PROD }}
        deploy-port: ${{ secrets.DEPLOY_REMOTE_PORT_PROD }}
        deploy-host-path: ${{ secrets.DEPLOY_REMOTE_PATH_PROD  }}
        deploy-host-backup-path: ${{ secrets.DEPLOY_REMOTE_BACKUP_DIR_PROD }}
        deploy-host-user: ${{ secrets.DEPLOY_REMOTE_USER_PROD }}
        deploy-host-user-key: ${{ secrets.DEPLOY_KEY_PROD }}
        deploy-host-web-server-user: ${{ secrets.WEB_SERVER_USER_PROD }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        acf-url: ${{ secrets.ACF_URL }}

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

  